// Shared app bootstrap: fetch the dataset once and hand it to the views.
// The dataset is generated by build_dataset.py and served as a static file.

const DATASET_URL = "data/items.json";

/** Fetch the dataset. Returns {metadata, items}. */
async function loadDataset() {
  const res = await fetch(DATASET_URL, { cache: "no-cache" });
  if (!res.ok) {
    throw new Error(`Failed to load dataset (${res.status} ${res.statusText})`);
  }
  return res.json();
}

// A tiny event bus so views can await the dataset without ordering assumptions.
const App = {
  dataset: null,
  _waiters: [],
  ready(cb) {
    if (this.dataset) cb(this.dataset);
    else this._waiters.push(cb);
  },
  _resolve(dataset) {
    this.dataset = dataset;
    this._waiters.forEach((cb) => cb(dataset));
    this._waiters = [];
  },
};

window.App = App;

loadDataset()
  .then((dataset) => {
    const info = document.getElementById("dataset-info");
    if (info) {
      const m = dataset.metadata || {};
      info.textContent = `${m.item_count ?? dataset.items.length} items`;
    }
    App._resolve(dataset);
  })
  .catch((err) => {
    const status = document.getElementById("browse-status");
    if (status) status.textContent = `Error loading dataset: ${err.message}`;
    console.error(err);
  });
