// Shared app bootstrap: fetch the dataset once and hand it to the views.
// The dataset is generated by build_dataset.py and served as a static file.

// App build version — date-based mmddyyyy.x (bump on every deployed build).
const BUILD = "08292026.10";

const DATASET_URL = "data/items.json";

/** Fetch the dataset. Returns {metadata, items}. */
async function loadDataset() {
  const res = await fetch(DATASET_URL, { cache: "no-cache" });
  if (!res.ok) {
    throw new Error(`Failed to load dataset (${res.status} ${res.statusText})`);
  }
  return res.json();
}

// A tiny event bus so views can await the dataset without ordering assumptions.
const App = {
  dataset: null,
  _waiters: [],
  ready(cb) {
    if (this.dataset) cb(this.dataset);
    else this._waiters.push(cb);
  },
  _resolve(dataset) {
    this.dataset = dataset;
    this._waiters.forEach((cb) => cb(dataset));
    this._waiters = [];
  },
};

// --- Tabs (Solver | Item Browser) --------------------------------------------
// Pure helpers, unit-tested in tests/tabs.test.js. The DOM wiring below consumes
// them; keeping the transition logic pure means it can be verified without a DOM.
const TAB_IDS = ["solver", "browse"];

/** The tab that should be active after clicking `clickedId`. Idempotent; an
 *  unknown id leaves the current tab active. */
function activeTab(currentId, clickedId, tabIds = TAB_IDS) {
  return tabIds.includes(clickedId) ? clickedId : currentId;
}

/** Roving-focus target for an arrow/Home/End keypress on the tablist (WAI-ARIA
 *  tabs pattern, automatic activation). Non-navigation keys return currentId. */
function nextTab(currentId, key, tabIds = TAB_IDS) {
  const i = tabIds.indexOf(currentId);
  if (i < 0) return currentId;
  const last = tabIds.length - 1;
  switch (key) {
    case "ArrowRight":
    case "ArrowDown":
      return tabIds[i === last ? 0 : i + 1];
    case "ArrowLeft":
    case "ArrowUp":
      return tabIds[i === 0 ? last : i - 1];
    case "Home":
      return tabIds[0];
    case "End":
      return tabIds[last];
    default:
      return currentId;
  }
}

// Browser-only wiring. Guarded so Node test `require` of this file exercises the
// pure helpers above without touching fetch/document.
if (typeof window !== "undefined" && typeof document !== "undefined") {
  window.App = App;

  const initTabs = () => {
    const tablist = document.querySelector('[role="tablist"]');
    if (!tablist) return;
    const tabs = Array.from(tablist.querySelectorAll('[role="tab"]'));
    const panel = (id) => document.getElementById(id);

    // Activate a tab id: set aria-selected + roving tabindex, hide the other
    // panel so AT and Tab order don't reach it, optionally move focus.
    const activate = (id, moveFocus) => {
      tabs.forEach((t) => {
        const on = t.getAttribute("aria-controls") === id;
        t.setAttribute("aria-selected", on ? "true" : "false");
        t.tabIndex = on ? 0 : -1;
        if (on && moveFocus) t.focus();
        const p = panel(t.getAttribute("aria-controls"));
        if (p) p.hidden = !on;
      });
    };

    tablist.addEventListener("click", (e) => {
      const tab = e.target.closest('[role="tab"]');
      if (!tab) return;
      const current = tabs.find((t) => t.getAttribute("aria-selected") === "true");
      const currentId = current && current.getAttribute("aria-controls");
      activate(activeTab(currentId, tab.getAttribute("aria-controls")), false);
    });

    tablist.addEventListener("keydown", (e) => {
      const current = tabs.find((t) => t.getAttribute("aria-selected") === "true");
      const currentId = current && current.getAttribute("aria-controls");
      const target = nextTab(currentId, e.key);
      if (target !== currentId) {
        e.preventDefault();
        activate(target, true);
      }
    });

    // Initial state: first tab active, others' panels hidden.
    activate(TAB_IDS[0], false);
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initTabs);
  } else {
    initTabs();
  }

  loadDataset()
    .then((raw) => {
      // U3 — normalize the near-native dataset at load: parse each native affix
      // string into numeric value + unit and attach the legacy aliases the
      // solver/model/UI still read. The ONLY place legacy names survive.
      const dataset = (window.DatasetNormalizer
        ? window.DatasetNormalizer.normalizeDataset(raw)
        : raw);
      // #88 U1/U2 — classify override-eligibility once per pool load. It has to
      // run HERE rather than inside normalizeDataset: the boolean-composite
      // components only exist after that function has generated them, and the
      // classification must see them to refuse them.
      if (window.Overrides) window.Overrides.classifyPool(dataset);
      // #428 U1 (R25) — the footer's item count is gone. A catalog size is a fact
      // about this repository, not about the player's build; the per-result
      // coverage disclosure (results.js coverageNote) is where a number that
      // describes the SOLVE still belongs.
      // #428 U2 (R28) — the stamp is a bare value beside its own label element,
      // not a run-on " · Build X" fragment appended to a sentence.
      const build = document.getElementById("build-info");
      if (build) build.textContent = BUILD;
      App._resolve(dataset);
    })
    .catch((err) => {
      const status = document.getElementById("browse-status");
      if (status) status.textContent = `Error loading dataset: ${err.message}`;
      console.error(err);
    });
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { activeTab, nextTab, TAB_IDS, App };
}
